echo "Creating EC2 instance..."
AMI_ID="ami-09c813fb71547fc4f"
INSTANCE_TYPE="t2.micro"
SECURITY_GROUP_IDS="sg-00c18b23c2b3c13c0"
INSTANCE_NAME="Shell-Script-EC2-Demo"
aws ec2 run-instances "$AMI_ID" "$INSTANCE_TYPE" "$SECURITY_GROUP_IDS" "$INSTANCE_NAME"
echo "EC2 instance creation completed."